### ISSUE TITLE
future wish

### ISSUE THREAD

**Issue by autro21** [Sharaf-Mansour/CVBuilder#16]
send generated CV to my mail

**Comment by Sharaf-Mansour** [comment]
The CV can be downloaded locally from the application as PDF or Raw Format. It has 0 connection to live server.
The current model is fully ruining on your local offline environment. (Serverless application).
So a smart way to do it is by making the app communicate with your mail application and attach the PDF to it. 
But again. Is this really needed ? you can use your native Device functions such as share/open in.
